### ISSUE TITLE
mutify not working

### ISSUE THREAD

**Issue by jarviser** [sijk/mutify-osx#1]
http://open.spotify.com/track/4EcwMZC5srOdOVUTIkQWkW

**Comment by sijk** [comment]
Yes, Spotify changed a while back so that it no longer emits track change notifications for ads. I have a plan for a possible work-around but I have other priorities at the moment. I'll try to fix this when I get time. Alternatively, patches are welcome :)

**Comment by sijk** [comment]
I've updated Mutify to work with the latest version of Spotify. Download the latest installer from http://sijk.github.io/mutify-osx/.
